/-
  AiProposes.lean — "the AI proposes, the kernel disposes."
  ----------------------------------------------------------------------------
  The literal answer to "how do I trust what an AI produced?": don't trust the
  AI's reasoning — make it hand you an artifact a tiny, dumb, trusted checker can
  verify. For Lean proofs that checker already exists: the **kernel**. And
  `#print axioms` is the *audit* — it reports exactly what a proof rests on.

  Three things this module makes concrete:
    1. A real proof generated by an LLM (this assistant), accepted by the kernel.
    2. The audit reveals HOW a proof was obtained, not just THAT it typechecks —
       a proof that reached for the compiler shows the extra axiom.
    3. Wrong proofs are refused outright; cheating (a hidden `sorry`) is exposed
       by the axiom list. AI confidence is irrelevant; the audit is the truth.
-/

/-! ## 1. An AI-generated proof, kernel-checked

`sumOdds n` adds the first `n` odd numbers. The theorem — that this equals `n²` —
and its inductive proof below were generated by an LLM. The kernel checked it.
You trusted the kernel, not the model. -/

def sumOdds : Nat → Nat
  | 0 => 0
  | n + 1 => sumOdds n + (2 * n + 1)

theorem sumOdds_eq (n : Nat) : sumOdds n = n * n := by
  induction n with
  | zero => rfl
  | succ k ih =>
    simp only [sumOdds, ih, Nat.succ_mul, Nat.mul_succ]
    omega

#print axioms sumOdds_eq   -- 'sumOdds_eq' does not depend on... → [propext, Quot.sound]

/-! ## 2. The audit reveals *how* — not just *that*

This fact is also true, but the proof reached for the compiler (`native_decide`).
The kernel accepts the result, and the audit honestly surfaces the extra trust
(`ofReduceBool`) — so an AI cannot quietly lean on more than it admits. -/

theorem big_sum : (List.range 1000).foldl (· + ·) 0 = 499500 := by native_decide

#print axioms big_sum   -- adds `Lean.ofReduceBool` — the audit shows the compiler was trusted.

/-! ## 3. Wrong is refused; cheating is exposed  (try these yourself)

**Wrong proofs are refused.** An AI might confidently emit a *false* claim:
```
theorem oops (n : Nat) : sumOdds n = n + n := by
  induction n with
  | zero => rfl
  | succ k ih => simp [sumOdds, ih]   -- fails: the claim is false (e.g. n=3: 9 ≠ 6)
```
No tactic sequence makes a false statement typecheck. The kernel simply refuses
it — confidence, fluency, and a plausible-looking script change nothing.

**Cheating is exposed.** An AI might paper over a gap:
```
theorem sneaky (n : Nat) : sumOdds n = n * n := by sorry
```
This "compiles" (with a warning), but `#print axioms sneaky` lists `sorryAx` —
the audit reveals the proof is hollow. Likewise an unexpected `Classical.choice`
or `ofReduceBool` in the axiom list tells you the proof leaned on something you
may not have wanted. **The axiom list, not the AI's say-so, is the trust boundary.**
-/
